/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as AuthenticatedSeriesRouteImport } from './routes/_authenticated/series'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedFilmesRouteImport } from './routes/_authenticated/filmes'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedSerieIdRouteImport } from './routes/_authenticated/serie.$id'
import { Route as AuthenticatedWatchTypeIdRouteImport } from './routes/_authenticated/watch.$type.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeriesRoute = AuthenticatedSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmesRoute = AuthenticatedFilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSerieIdRoute = AuthenticatedSerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchTypeIdRoute =
  AuthenticatedWatchTypeIdRouteImport.update({
    id: '/watch/$type/$id',
    path: '/watch/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/conta': typeof AuthenticatedContaRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/series': typeof AuthenticatedSeriesRoute
  '/tv': typeof AuthenticatedTvRoute
  '/serie/$id': typeof AuthenticatedSerieIdRoute
  '/watch/$type/$id': typeof AuthenticatedWatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/conta': typeof AuthenticatedContaRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/series': typeof AuthenticatedSeriesRoute
  '/tv': typeof AuthenticatedTvRoute
  '/': typeof AuthenticatedIndexRoute
  '/serie/$id': typeof AuthenticatedSerieIdRoute
  '/watch/$type/$id': typeof AuthenticatedWatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/filmes': typeof AuthenticatedFilmesRoute
  '/_authenticated/perfis': typeof AuthenticatedPerfisRoute
  '/_authenticated/series': typeof AuthenticatedSeriesRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/serie/$id': typeof AuthenticatedSerieIdRoute
  '/_authenticated/watch/$type/$id': typeof AuthenticatedWatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conta'
    | '/filmes'
    | '/perfis'
    | '/series'
    | '/tv'
    | '/serie/$id'
    | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/conta'
    | '/filmes'
    | '/perfis'
    | '/series'
    | '/tv'
    | '/'
    | '/serie/$id'
    | '/watch/$type/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conta'
    | '/_authenticated/filmes'
    | '/_authenticated/perfis'
    | '/_authenticated/series'
    | '/_authenticated/tv'
    | '/_authenticated/'
    | '/_authenticated/serie/$id'
    | '/_authenticated/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series': {
      id: '/_authenticated/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis': {
      id: '/_authenticated/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AuthenticatedPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filmes': {
      id: '/_authenticated/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof AuthenticatedFilmesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/serie/$id': {
      id: '/_authenticated/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof AuthenticatedSerieIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/$type/$id': {
      id: '/_authenticated/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof AuthenticatedWatchTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedFilmesRoute: typeof AuthenticatedFilmesRoute
  AuthenticatedPerfisRoute: typeof AuthenticatedPerfisRoute
  AuthenticatedSeriesRoute: typeof AuthenticatedSeriesRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSerieIdRoute: typeof AuthenticatedSerieIdRoute
  AuthenticatedWatchTypeIdRoute: typeof AuthenticatedWatchTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedFilmesRoute: AuthenticatedFilmesRoute,
  AuthenticatedPerfisRoute: AuthenticatedPerfisRoute,
  AuthenticatedSeriesRoute: AuthenticatedSeriesRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSerieIdRoute: AuthenticatedSerieIdRoute,
  AuthenticatedWatchTypeIdRoute: AuthenticatedWatchTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
